"""Add mcp_token to User

Revision ID: b0bfebbaa9db
Revises: ac23802e6154
Create Date: 2026-04-04 20:28:47.349111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0bfebbaa9db'
down_revision = 'ac23802e6154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mcp_token', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mcp_token')

    # ### end Alembic commands ###
